Repository aswathcm29/JournalForge, pull requests merged in 2024-10, with the labels that each got.

#63 feat:#60 added
  frontend/package-lock.json
  frontend/src/components/Navbar.jsx
  frontend/src/components/util/MagneticEffect.jsx
Labels: enhancement, gssoc-etd, hacktoberfest-accepted, level-1

#65 password toggle show hide button added : Done #40 which is assigned to me.
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Logincred/Login.jsx
  frontend/src/components/Logincred/Signup.jsx
Labels: enhancement, good first issue, gssoc-etd, hacktoberfest-accepted, level-1

#153 Changed the login page title
  frontend/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level1
